version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=wordpress
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=edu
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mysql_data:
  mariadb_data:
